spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_S3_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB